Repository codestates-seb/seb44_main_013, pull requests merged in 2023-07, with the labels that each got.

#8 [FRONT] Design : global style 선정
  client/src/commons/styles/Globalcolor.tsx
Labels: FE

#12 [FRONT] Design: Footer UI 컴포넌생성
  client/src/commons/Footer.tsx
Labels: FE

#15 [FRONT] feat: 북마크 레이아웃 구현
  .github/ISSUE_TEMPLATE/이슈-기능-작성.md
  client/src/components/Bookmark.tsx
Labels: FE

#17 [add] 메인페이지 - 헤더 구현
  client/src/assets/logo.png
  client/src/assets/userImg.jpg
  client/src/commons/atoms/buttons/Button.styled.tsx
  client/src/commons/atoms/buttons/login/LoginBtn.styled.tsx
  client/src/commons/atoms/buttons/login/LoginBtn.tsx
  client/src/commons/atoms/header/Header.styled.tsx
  client/src/commons/atoms/header/Header.tsx
  client/src/commons/atoms/logo/Logo.styled.tsx
  client/src/commons/atoms/logo/Logo.tsx
  client/src/commons/atoms/user/UserImg.styled.tsx
  client/src/commons/atoms/user/UserImg.tsx
  client/src/components/search/Search.styled.tsx
  client/src/components/search/Search.tsx
  client/src/pages/community/Community.styled.tsx
  client/src/pages/community/Community.tsx
Labels: FE

#22 Add: 게시판 관련 페이지 공통 헤더 구현
  client/src/commons/atoms/header/CHeader.styled.tsx
  client/src/commons/atoms/header/CHeader.tsx
  client/src/commons/atoms/header/Header.styled.tsx
Labels: FE

#27 Add: 커뮤니티 페이지 생성
  client/src/components/search/Search.styled.tsx
  client/src/pages/404/Loading.tsx
  client/src/pages/community/Community.styled.tsx
  client/src/pages/community/Community.tsx
Labels: FE

#29 Design: 게시판 목록의 writing Button 생성
  client/src/commons/atoms/buttons/Button.styled.tsx
  client/src/commons/atoms/buttons/PurpleBtn.tsx
  client/src/commons/atoms/buttons/writing/writingBtn.tsx
Labels: FE

#30 Design: community views(조회수) 구현
  client/src/components/views/Views.styled.tsx
  client/src/components/views/Views.tsx
Labels: FE

#31 Design: 게시물 상세 페이지의 삭제/수정 버튼 + 및 댓글 저장 버튼 생성
  client/src/commons/atoms/buttons/Button.styled.tsx
  client/src/commons/atoms/buttons/PurpleBtn.tsx
  client/src/commons/atoms/buttons/writing/DeleteBtn.tsx
  client/src/commons/atoms/buttons/writing/EditBtn.tsx
  client/src/commons/atoms/buttons/writing/SaveBtn.tsx
  client/src/commons/atoms/buttons/writing/writingBtn.tsx
Labels: FE

#36 Design: Community Detail Contents form 구현
  client/src/components/detailContents/DetailContents.styled.tsx
  client/src/components/detailContents/DetailContents.tsx
  client/src/components/views/Views.styled.tsx
  client/src/components/views/Views.tsx
Labels: FE

#43 Add: Community 페이지 취합 작업
  client/.storybook/main.ts
  client/src/assets/react.svg
  client/src/commons/atoms/Image.tsx
  client/src/commons/atoms/Label.tsx
  client/src/commons/atoms/buttons/Button.styled.tsx
  client/src/commons/atoms/buttons/PurpleBtn.tsx
  client/src/commons/atoms/buttons/writing/writingBtn.tsx
  client/src/commons/atoms/footer/Footer.styled.tsx
  client/src/commons/molecules/UserProfile.tsx
  client/src/commons/styles/Containers.styled.tsx
  client/src/commons/styles/StyleList.ts
  client/src/components/communityItem/CommunityItem.styled.tsx
  client/src/components/communityItem/CommunityItem.tsx
  client/src/components/navbar/CategoryNavBar.tsx
  client/src/components/search/Search.styled.tsx
  client/src/components/views/Views.styled.tsx
  client/src/components/views/Views.tsx
  client/src/pages/404/Loading.tsx
  client/src/pages/community/Community.styled.tsx
  client/src/pages/community/Community.tsx
  client/src/pages/main/Main.tsx
  client/src/stories/components/NavBar.stories.tsx
  client/src/stories/components/UserProfile.stories.tsx
  client/src/types/StyleType.ts
Labels: FE

#44 Design: login page 구조 작업
  client/src/assets/googleLogo.png
  client/src/commons/atoms/backText/BackText.styled.tsx
  client/src/commons/atoms/backText/BackText.tsx
  client/src/commons/atoms/logo/GoogleLogo.tsx
  client/src/commons/atoms/logo/Logo.styled.tsx
  client/src/components/login/LoginGoogleForm.styled.tsx
  client/src/components/login/LoginGoogleForm.tsx
  client/src/pages/login/Login.styled.tsx
  client/src/pages/login/Login.tsx
  client/src/pages/login/nothing
  client/src/types/index.ts
Labels: FE

#48 Design: 마이페이지 프로필 구현
  client/src/components/detailContents/DetailContents.styled.tsx
  client/src/components/detailContents/DetailContents.tsx
  client/src/components/detailGuide/DetailGuide.styled.tsx
  client/src/components/detailGuide/DetailGuide.tsx
  client/src/components/mypageProfile/MypageProfile.styled.tsx
  client/src/components/mypageProfile/MypageProfile.tsx
  client/src/pages/community-detail/CommunityDetail.styled.tsx
  client/src/pages/community-detail/CommunityDetail.tsx
Labels: FE

#51 Design: 마이페이지의 내 아이템 관리 부분의 아이템 컴포넌트 생성
  client/src/assets/googleLogo.png
  client/src/assets/tempItem.png
  client/src/commons/atoms/backText/BackText.styled.tsx
  client/src/commons/atoms/backText/BackText.tsx
  client/src/commons/atoms/buttons/Button.styled.tsx
  client/src/commons/atoms/logo/GoogleLogo.tsx
  client/src/commons/atoms/logo/Logo.styled.tsx
  client/src/components/login/LoginGoogleForm.styled.tsx
  client/src/components/login/LoginGoogleForm.tsx
  client/src/components/mypageItem/Mypage.styled.tsx
  client/src/components/mypageItem/MypageItem.tsx
  client/src/pages/login/Login.styled.tsx
  client/src/pages/login/Login.tsx
  client/src/pages/signup/SignUp.styled.tsx
  client/src/pages/signup/SignUp.tsx
  client/src/types/index.ts
  client/tailwind.config.js
Labels: FE

#66 Design: mypage의 페이지네이션 UI 구현
  client/src/commons/styles/Containers.styled.tsx
  client/src/components/pagenation/Pagenation.styled.tsx
  client/src/components/pagenation/Pagenation.tsx
  client/src/pages/mypage/Mypage.tsx
Labels: FE

#67 Add: 마이페이지 브랜치 fe-dev 로 merge 작업
  client/src/assets/tempItem.png
  client/src/commons/atoms/footer/Footer.styled.tsx
  client/src/commons/styles/Containers.styled.tsx
  client/src/components/detailContents/DetailContents.styled.tsx
  client/src/components/mypage-community/CommunityList.styled.tsx
  client/src/components/mypage-community/CommunityList.tsx
  client/src/components/mypageIntroduce/MypageIntroduce.styled.tsx
  client/src/components/mypageIntroduce/MypageIntroduce.tsx
  client/src/components/mypageItem/MypageItem.styled.tsx
  client/src/components/mypageItem/MypageItem.tsx
  client/src/components/mypageProfile/MypageProfile.styled.tsx
  client/src/components/mypageProfile/MypageProfile.tsx
  client/src/components/pagenation/Pagenation.styled.tsx
  client/src/components/pagenation/Pagenation.tsx
  client/src/index.css
  client/src/pages/main/Main.tsx
  client/src/pages/mypage/MyPage.styled.tsx
  client/src/pages/mypage/Mypage.tsx
  client/src/types/index.ts
  client/tailwind.config.js
  server/HELP.md
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  server/src/main/java/com/portfolly/server/ServerApplication.java
  server/src/main/resources/application.properties
  server/src/test/java/com/portfolly/server/ServerApplicationTests.java
Labels: FE

#91 Add: Routes 연결 작업 1차 제출
  client/src/App.tsx
  client/src/commons/atoms/header/CHeader.tsx
  client/src/commons/atoms/header/Header.styled.tsx
  client/src/commons/atoms/header/Header.tsx
  client/src/commons/atoms/user/UserImg.styled.tsx
  client/src/commons/atoms/user/UserImg.tsx
  client/src/commons/styles/Containers.styled.tsx
  client/src/commons/styles/MainLayout.tsx
  client/src/components/Dropdown.tsx
  client/src/components/headerDropdown/HeaderDropdown.styled.tsx
  client/src/components/headerDropdown/HeaderDropdown.tsx
  client/src/pages/community-detail/CommunityDetail.tsx
  client/src/pages/community-list/CommunityList.tsx
  client/src/pages/community-main/CommunityMain.styled.tsx
  client/src/pages/community-main/CommunityMain.tsx
  client/src/pages/login/Login.tsx
  client/src/pages/main/Main.tsx
  client/src/pages/mypage/Mypage.tsx
  client/src/pages/signup/SignUp.styled.tsx
  client/src/pages/signup/SignUp.tsx
  client/src/types/index.ts
Labels: FE

#96 Design: Header UI 수정 완 및 토스
  client/src/commons/atoms/header/Header.styled.tsx
  client/src/commons/atoms/header/Header.tsx
  client/src/components/search/Search.styled.tsx
Labels: FE

#100 Design: UI 추합 수정 작업 3차
  client/src/commons/molecules/CommentWriteBox.tsx
  client/src/commons/molecules/UserProfile.tsx
  client/src/commons/styles/Containers.styled.tsx
  client/src/commons/styles/Inputs.styled.tsx
  client/src/pages/community-detail/CommunityDetail.styled.tsx
  client/src/pages/community-detail/CommunityDetail.tsx
  client/src/pages/community-main/CommunityMain.styled.tsx
  client/src/pages/community-main/CommunityMain.tsx
Labels: FE

#106 Design: 게시판 등록/수정 페이지 레이아웃 수정
  client/src/components/detailGuide/DetailGuide.styled.tsx
  client/src/pages/community-add/AddCommunity.styled.tsx
  client/src/pages/community-add/AddCommunity.tsx
Labels: FE

#108 Design: UI 추합 작업 4차
  client/src/App.tsx
  client/src/commons/atoms/Label.tsx
  client/src/commons/atoms/Typography.tsx
  client/src/commons/atoms/buttons/revise-remove/RemoveBtn.tsx
  client/src/commons/atoms/buttons/revise-remove/ReviseBtn.tsx
  client/src/commons/atoms/header/CHeader.styled.tsx
  client/src/commons/atoms/header/CHeader.tsx
  client/src/commons/molecules/Comment.tsx
  client/src/commons/molecules/UserProfile.tsx
  client/src/commons/styles/Inputs.styled.tsx
  client/src/components/detailContents/DetailContents.styled.tsx
  client/src/pages/community-add/AddCommunity.tsx
  client/src/pages/community-detail/CommunityDetail.styled.tsx
  client/src/pages/community-detail/CommunityDetail.tsx
  client/src/pages/community-main/CommunityMain.tsx
  client/src/pages/mypage/MyPage.styled.tsx
  client/src/types/index.ts
Labels: FE

#112 Feat: Portfolio-Detail-Page에 포트폴리오에 대한 데이터를 GET요청 한다.
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/header/LogoHeader.tsx
  client/src/pages/portfolio-detail/PortfolioDetail.styled.tsx
  client/src/pages/portfolio-detail/PortfolioDetail.tsx
Labels: FE

#113 Feat: Portfolio Detail Page에 존재하는 각종 버튼에 링크를 넣는다.
  client/src/App.tsx
  client/src/commons/atoms/Image.tsx
  client/src/commons/atoms/Label.tsx
  client/src/commons/atoms/Typography.tsx
  client/src/commons/atoms/buttons/Button.styled.tsx
  client/src/commons/atoms/buttons/LikeBtn.tsx
  client/src/commons/atoms/buttons/PurpleBtn.tsx
  client/src/commons/molecules/Comment.tsx
  client/src/commons/molecules/CommentWriteBox.tsx
  client/src/commons/molecules/UserProfile.tsx
  client/src/components/bookmark/Bookmark.styled.tsx
  client/src/components/communityItem/CommunityItem.tsx
  client/src/hooks/useLikeBtn.tsx
  client/src/mocks/data.ts
  client/src/mocks/handlers.ts
  client/src/pages/community-detail/CommunityDetail.tsx
  client/src/pages/portfolio-detail/PortfolioDetail.tsx
  client/src/types/UserInterface.ts
  client/src/types/index.ts
Labels: FE

#116 Fix: UserProfile이 들어가는 페이지에 임시 user props를 전달한다.
  client/src/commons/molecules/Comment.tsx
  client/src/commons/molecules/CommentWriteBox.tsx
  client/src/components/communityItem/CommunityItem.tsx
  client/src/pages/community-detail/CommunityDetail.tsx
  client/src/pages/portfolio-detail/PortfolioDetail.tsx
Labels: FE

#114 Feat: UserProfile 프로필 이미지 & 닉네임 클릭 시 마이페이지로 이동한다.
  client/src/App.tsx
  client/src/commons/atoms/Image.tsx
  client/src/commons/atoms/Label.tsx
  client/src/commons/molecules/UserProfile.tsx
  client/src/hooks/useLikeBtn.tsx
  client/src/mocks/data.ts
  client/src/mocks/handlers.ts
  client/src/pages/portfolio-detail/PortfolioDetail.tsx
  client/src/types/UserInterface.ts
  client/src/types/index.ts
Labels: FE

#118 Feat: 좋아요 버튼 기능을 구현한다.
  client/src/commons/atoms/buttons/LikeBtn.tsx
  client/src/commons/styles/Containers.styled.tsx
  client/src/hooks/useLikeBtn.tsx
  client/src/mocks/data.ts
  client/src/mocks/handlers.ts
  client/src/pages/portfolio-detail/PortfolioDetail.tsx
  client/src/utils/ApiService.tsx
Labels: FE

#119 Feat: 북마크 버튼 기능을 구현한다.
  client/src/commons/atoms/buttons/Bookmark.tsx
  client/src/components/appItem/AppItem.tsx
  client/src/components/bookmark/Bookmark.styled.tsx
  client/src/components/bookmark/Bookmark.tsx
  client/src/components/photoItem/PhotoItem.tsx
  client/src/components/webItem/WebItem.tsx
  client/src/hooks/useBookmarkBtn.tsx
  client/src/mocks/data.ts
  client/src/mocks/handlers.ts
  client/src/pages/portfolio-detail/PortfolioDetail.tsx
Labels: FE

#120 Fix: LikeBtn & useLikeBtn 두 개의 PropsType을 동일화한다.
  client/src/commons/atoms/buttons/LikeBtn.tsx
  client/src/hooks/useLikeBtn.tsx
  client/src/mocks/data.ts
  client/src/pages/portfolio-detail/PortfolioDetail.tsx
Labels: FE

#122 Feat: 게시판 메인 페이지 목록 조회 기능 구현
  client/src/App.tsx
  client/src/components/communityItem/CommunityItem.tsx
  client/src/components/views/Views.tsx
  client/src/pages/community-main/CommunityMain.tsx
Labels: Middle, FE

#130 Feat: Editor에서 텍스트를 입력받아 TitleForm에 전달한다.
  client/src/components/editor/QuillEditor.tsx
  client/src/components/editor/TitleForm.tsx
  client/src/pages/portfolio-edit/PortfolioEdit.tsx
  client/src/types/QuillPropsType.ts
  client/src/types/index.ts
Labels: FE

#136 Feat: 게시판 메인페이지 검색창 기능 구현
  client/src/components/search/Search.tsx
  client/src/pages/community-add/AddCommunity.tsx
  client/src/pages/community-main/CommunityMain.tsx
Labels: FE

#127 Feat: 게시판 상세 페이지 조회 기능 구현
  client/src/App.tsx
  client/src/commons/atoms/Card.tsx
  client/src/commons/atoms/buttons/writing/SaveBtn.tsx
  client/src/commons/molecules/Comment.tsx
  client/src/commons/molecules/CommentWriteBox.tsx
  client/src/components/CommentBox.tsx
  client/src/components/communityItem/CommunityItem.tsx
  client/src/components/detailContents/DetailContents.tsx
  client/src/mocks/data.ts
  client/src/mocks/handlers.ts
  client/src/pages/community-detail/CommunityDetail.tsx
  client/src/pages/community-main/CommunityMain.tsx
  client/src/types/index.ts
Labels: Middle, FE

#142 Fix: 메인페이지, 커뮤니티페이지 백그라운드 이미지 변경
  client/src/assets/communitymainimg.png
  client/src/assets/mainimg.png
  client/src/pages/community-main/CommunityMain.tsx
Labels: FE

#148 Feat: 포트폴리오 상세보기 페이지에 구현한 기능을 등록한다.
  client/package.json
  client/src/App.tsx
  client/src/commons/atoms/Image.tsx
  client/src/commons/atoms/Label.tsx
  client/src/commons/atoms/Typography.tsx
  client/src/commons/atoms/buttons/Bookmark.tsx
  client/src/commons/atoms/buttons/Button.styled.tsx
  client/src/commons/atoms/buttons/LikeBtn.tsx
  client/src/commons/molecules/Comment.tsx
  client/src/commons/molecules/CommentWriteBox.tsx
  client/src/commons/styles/Containers.styled.tsx
  client/src/components/appItem/AppItem.tsx
  client/src/components/bookmark/Bookmark.styled.tsx
  client/src/components/bookmark/Bookmark.tsx
  client/src/components/communityItem/CommunityItem.tsx
  client/src/components/header/LogoHeader.tsx
  client/src/components/photoItem/PhotoItem.tsx
  client/src/components/webItem/WebItem.tsx
  client/src/hooks/useBookmarkBtn.tsx
  client/src/hooks/useLikeBtn.tsx
  client/src/mocks/data.ts
  client/src/mocks/handlers.ts
  client/src/pages/community-detail/CommunityDetail.tsx
  client/src/pages/portfolio-detail/PortfolioDetail.styled.tsx
  client/src/pages/portfolio-detail/PortfolioDetail.tsx
  client/src/types/index.ts
  client/src/utils/ApiService.tsx
Labels: FE

#149 Feat: 포트폴리오 작성/수정 페이지 기능을 추가한다.
  client/src/App.tsx
  client/src/commons/atoms/dropdown/DropDownBox.tsx
  client/src/commons/atoms/dropdown/DropDownItem.tsx
  client/src/commons/molecules/CategoryDropDown.tsx
  client/src/commons/molecules/Tag.tsx
  client/src/commons/molecules/UserProfile.tsx
  client/src/commons/styles/Buttons.styled.tsx
  client/src/components/editor/QuillEditor.tsx
  client/src/components/editor/TitleForm.tsx
  client/src/hooks/useTagSelect.tsx
  client/src/mocks/data.ts
  client/src/mocks/handlers.ts
  client/src/modules/CategorySlice.ts
  client/src/modules/Slice.ts
  client/src/modules/TagSlice.ts
  client/src/modules/index.ts
  client/src/pages/portfolio-detail/PortfolioDetail.tsx
  client/src/pages/portfolio-edit/PortfolioEdit.tsx
  client/src/query/Mutation.tsx
  client/src/query/portfolioMutation.tsx
  client/src/types/QuillPropsType.ts
  client/src/types/UserInterface.ts
  client/src/types/getDataType.ts
  client/src/types/index.ts
  client/src/types/reduxStateType.ts
Labels: FE

#153 Rename: 게시판 부분 APi 명세서에 따른 변수 이름 변경 및 주석 정리
  client/src/App.tsx
  client/src/commons/molecules/Comment.tsx
  client/src/components/CommentBox.tsx
  client/src/components/communityItem/CommunityItem.tsx
  client/src/mocks/data.ts
  client/src/mocks/handlers.ts
  client/src/mocks/infiniteScrollData.ts
  client/src/pages/community-detail/CommunityDetail.tsx
  client/src/types/index.ts
  client/src/utils/ApiService.tsx
Labels: Middle, FE

#159 fix: 커뮤니티 아이템 변수 명 수정
  client/src/components/communityItem/CommunityItem.tsx
  client/src/mocks/handlers.ts
Labels: FE

#161 Fix: 파일명 변경, 경로 수정
  client/src/components/CommentBox.tsx
  client/src/modules/categorySlice.ts
  client/src/modules/tagSlice.ts
  client/src/utils/ApiService.tsx
Labels: FE

#162 Feat: 로그인 상태 전역 관리 1차 작성
  client/src/commons/atoms/header/CHeader.tsx
  client/src/commons/atoms/header/Header.tsx
  client/src/commons/molecules/Comment.tsx
  client/src/components/header/LogoHeader.tsx
  client/src/components/mypageIntroduce/MypageIntroduce.tsx
  client/src/mocks/handlers.ts
  client/src/modules/index.ts
  client/src/modules/loginSlice.ts
  client/src/pages/community-main/CommunityMain.tsx
  client/src/pages/mypage/Mypage.tsx
Labels: FE

#165 Feat: CommunityMain에서 게시판 별 구분 기능 구현
  client/src/commons/atoms/header/CHeader.tsx
  client/src/commons/atoms/header/Header.tsx
  client/src/components/communityItem/CommunityItem.tsx
  client/src/mocks/handlers.ts
  client/src/pages/community-main/CommunityMain.tsx
Labels: FE

#81 Design: mypage photo item 구현
  client/src/components/appItem/AppItem.stlyed.tsx
  client/src/components/appItem/AppItem.tsx
  client/src/components/mypageIntroduce/MypageIntroduce.styled.tsx
  client/src/components/mypageIntroduce/MypageIntroduce.tsx
  client/src/components/mypageProfile/MypageProfile.styled.tsx
  client/src/components/mypageProfile/MypageProfile.tsx
  client/src/components/photoItem/PhotoItem.tsx
  server/HELP.md
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  server/src/main/java/com/portfolly/server/ServerApplication.java
  server/src/main/resources/application.properties
  server/src/test/java/com/portfolly/server/ServerApplicationTests.java
Labels: FE

#166 Design: 앱 아이템, 그래픽아이템, 사진아이템 디자인 구현
  client/src/components/appItem/AppItem.stlyed.tsx
  client/src/components/graphicItem/GraphicItem.styled.tsx
  client/src/components/graphicItem/GraphicItem.tsx
Labels: FE

#168 Remove: 미선언 요소 주석 처리 및 불필요한 세미콜론 , 오타 수정 작업"
  client/src/commons/atoms/Label.tsx
  client/src/commons/atoms/buttons/Bookmark.tsx
  client/src/commons/atoms/buttons/top/TopBtn.tsx
  client/src/commons/molecules/MemberProfile.tsx
  client/src/commons/styles/layout/Layout.styled.tsx
  client/src/commons/styles/layout/MainLayout.tsx
  client/src/components/Temp.tsx
  client/src/components/appItem/AppItem.tsx
  client/src/components/detailGuide/DetailGuide.tsx
  client/src/components/photoItem/PhotoItem.tsx
  client/src/components/webItem/WebItem.tsx
  client/src/hooks/useTagSelect.tsx
  client/src/hooks/useToggle.tsx
  client/src/mocks/data.ts
  client/src/mocks/infiniteScrollData.ts
  client/src/pages/community-add/AddCommunity.tsx
  client/src/pages/community-detail/CommunityDetail.styled.tsx
  client/src/pages/community-main/CommunityMain.tsx
  client/src/query/portfolioMutation.tsx
  client/src/types/StyleType.ts
  client/src/types/index.ts
Labels: FE

#172 Design: 삭제 확인 모달창 구현
  client/src/commons/atoms/buttons/Button.styled.tsx
  client/src/components/deleteModal/DeleteModal.styled.tsx
  client/src/components/deleteModal/DeleteModal.tsx
  client/src/components/detailContents/DetailContents.tsx
  client/src/pages/community-add/AddCommunity.tsx
  client/src/pages/community-detail/CommunityDetail.tsx
Labels: FE

#183 Fix: 네트리파이 배포 위해에러 수정 및 쿠키, 구글 oauth package.json 추가
  client/package-lock.json
  client/package.json
  client/src/components/navbar/CategoryNavBar.tsx
  client/src/components/pagenation/Pagenation.tsx
  client/src/hooks/useToggle.tsx
  client/src/pages/community-main/CommunityMain.tsx
  client/src/types/portfolio.ts
Labels: FE

#192 Fix: 네틀리 파이 배포 준비 - communityDetail수정
  client/index.html
  client/src/App.tsx
  client/src/commons/atoms/header/CHeader.tsx
  client/src/commons/styles/layout/Layout.styled.tsx
  client/src/components/headerDropdown/HeaderDropdown.tsx
  client/src/components/login/LoginGoogleForm.styled.tsx
  client/src/components/login/LoginGoogleForm.tsx
  client/src/components/modal/AlertModal.tsx
  client/src/mocks/data.ts
  client/src/mocks/handlers.ts
  client/src/modules/loginSlice.ts
  client/src/pages/community-detail/CommunityDetail.tsx
  client/src/pages/login/Login.tsx
  client/src/pages/signup/SignUp.tsx
  client/src/utils/apiService.tsx
Labels: FE

#193 Feat: 로그인 기능 구현 1차
  client/src/components/login/LoginGoogleForm.tsx
Labels: FE

#195 Feat: 구글 OAuth get/post 설정
  client/src/App.tsx
  client/src/components/login/LoginGoogleForm.tsx
  client/src/mocks/handlers.ts
  client/src/pages/login/Login.tsx
  client/src/utils/apiService.tsx
  client/src/utils/cookie.tsx
Labels: FE

#212 Feat: 카테고리 메인 페이지 dummydata 구현
  client/src/components/appItem/AppItem.tsx
  client/src/components/graphicItem/GraphicItem.tsx
  client/src/components/photoItem/PhotoItem.tsx
  client/src/components/threeDitem/ThreeDITem.tsx
  client/src/components/webItem/WebItem.tsx
  client/src/mocks/handlers.ts
  client/src/mocks/infiniteScrollData.ts
  client/src/pages/main/Main.tsx
  client/src/utils/apiService.tsx
Labels: Bare Minimum, FE

#220 Feat: 게시판 상세 페이지 조회, 수정, 삭제 수정 완료
  client/package-lock.json
  client/src/components/detailContents/DetailContents.tsx
  client/src/pages/community-add/AddCommunity.tsx
  client/src/pages/community-detail/CommunityDetail.tsx
  client/src/pages/community-main/CommunityMain.tsx
Labels: FE

#222 Fix: 메인페이지 검색창 코드 수정, search 컴포넌트 함수 수정
  client/src/components/search/Search.tsx
  client/src/pages/community-main/CommunityMain.tsx
  client/src/pages/main/Main.tsx
Labels: FE

#245 Feat: 로그인 로직 1차 테스트 후 커밋
  client/src/App.tsx
  client/src/assets/datano.png
  client/src/assets/noComment.png
  client/src/components/comment/CommentBox.tsx
  client/src/components/login/LoginGoogleForm.tsx
  client/src/components/login/SelectRole.styled.tsx
  client/src/components/login/SelectRole.tsx
  client/src/mocks/handlers.ts
  client/src/modules/loginSlice.ts
  client/src/pages/community-detail/CommunityDetail.tsx
  client/src/pages/community-main/CommunityMain.tsx
  client/src/pages/gisun/Neon.tsx
  client/src/pages/login/Login.tsx
  client/src/pages/main/Main.tsx
  client/src/pages/signup/SignUp.tsx
  client/src/utils/apiService.tsx
  client/src/utils/axiosIntercept.tsx
Labels: FE

#254 Fix: 메인페이지 데이터 없을 때 띄우는 이미지 코드 수정
  client/src/pages/main/Main.styled.tsx
  client/src/pages/main/Main.tsx
Labels: FE

#257 Fix: 게시판 메인 데이터 없을 때 이미지 페이지
  client/src/pages/community-main/CommunityMain.styled.tsx
  client/src/pages/community-main/CommunityMain.tsx
Labels: FE

#258 Feat: 로그인 테스트 성공 임시 업로드
  client/src/components/header/CHeader.tsx
  client/src/components/header/Header.tsx
  client/src/components/headerDropdown/HeaderDropdown.tsx
  client/src/components/login/LoginGoogleForm.tsx
  client/src/components/login/SelectRole.tsx
  client/src/components/search/Search.tsx
  client/src/pages/main/Main.tsx
  client/src/store/loginSlice.ts
Labels: FE

#260 fix: search props 타입 수정
  client/src/components/search/Search.tsx
Labels: FE

#265 Feat: 이미지&동영상을 width:100%로 보이게 한다.
  client/src/assets/data/category.ts
  client/src/commons/atoms/buttons/Button.styled.tsx
  client/src/commons/molecules/dropdown/CategoryDropDown.tsx
  client/src/commons/molecules/profile/MemberProfile.tsx
  client/src/commons/molecules/tag/Tag.tsx
  client/src/components/editor/QuillEditor.tsx
  client/src/components/header/CHeader.styled.tsx
  client/src/components/titleForm/TitleForm.tsx
  client/src/components/titleForm/useTitleForm.ts
  client/src/hooks/useChangeHtmlContent.tsx
  client/src/hooks/useImageHandler.tsx
  client/src/mocks/data.ts
  client/src/mocks/handlers.ts
  client/src/pages/portfolio-detail/PortfolioDetail.styled.tsx
  client/src/pages/portfolio-detail/PortfolioDetail.tsx
  client/src/pages/portfolio-edit/PortfolioEdit.styled.tsx
  client/src/pages/portfolio-edit/PortfolioEdit.tsx
  client/src/store/categorySlice.ts
  client/src/store/portfolioSlice.ts
  client/src/types/index.ts
  client/src/types/initials.ts
  client/src/types/portfolio.ts
Labels: FE

#271 fix: 회원가입 link 경로 수정, 로그인 p태그 변경
  client/src/pages/login/Login.tsx
  client/src/pages/signup/SignUp.tsx
Labels: FE

#267 Feat: netlify 배포 proxy 설정준비
  client/netlify.toml
  client/src/assets/circleNoImg.png
  client/src/components/login/LoginGoogleForm.tsx
Labels: FE

#276 Fix: 네틀리파이 배포 에러 해결 작업
  client/src/commons/atoms/buttons/category/CategoryButton.tsx
  client/src/commons/molecules/comment/Comment.tsx
  client/src/commons/molecules/comment/CommentWriteBox.tsx
  client/src/components/comment/CommentBox.tsx
  client/src/components/communityItem/CommunityItem.tsx
  client/src/components/detailContents/DetailContents.tsx
  client/src/components/home-section/black-section/BlackSection.tsx
  client/src/components/navbar/CategoryNavBar.tsx
  client/src/mocks/data.ts
  client/src/mocks/handlers.ts
  client/src/pages/community-detail/CommunityDetail.tsx
  client/src/pages/community-main/CommunityMain.tsx
  client/src/pages/main/Main.tsx
  client/src/store/portfolioSlice.ts
  client/src/types/index.ts
Labels: FE

#353 Fix: community function
  client/src/components/communityItem/CommunityItem.styled.tsx
  client/src/components/communityItem/CommunityItem.tsx
  client/src/components/search/Search.tsx
  client/src/pages/community-add/AddCommunity.tsx
  client/src/pages/community-edit/EditCommunity.tsx
  client/src/pages/community-main/CommunityMain.styled.tsx
  client/src/pages/community-main/CommunityMain.tsx
Labels: FE

#354 fix: 메인 검색코드 수정
  client/src/components/search/Search.tsx
Labels: FE

#363 Fix: 댓글 PATCH, DELETE 수정
  client/src/commons/molecules/comment/Comment.tsx
  client/src/components/comment/CommentBox.tsx
Labels: FE

#365 Fe feat/community function
  client/src/commons/atoms/buttons/Button.styled.tsx
  client/src/components/detailContents/DetailContents.styled.tsx
  client/src/components/detailContents/DetailContents.tsx
  client/src/pages/community-main/CommunityMain.tsx
Labels: FE

#366 fix: 랜딩페이지 ui 수정
  client/src/commons/atoms/buttons/skip/SkipButton.styled.tsx
  client/src/commons/atoms/buttons/skip/SkipButton.tsx
  client/src/commons/atoms/portfolly/PortfollyBtn.tsx
  client/src/components/home-section/app-section/AppSection.styled.tsx
  client/src/pages/landingpage/LandingPage.styled.tsx
  client/src/pages/landingpage/LandingPage.tsx
Labels: FE

#372 Fix: comment-path url amend
  client/src/commons/molecules/comment/Comment.tsx
Labels: FE

#376 Feat: 파트너 회원만 포트폴리오 작성 버튼이 보이게 한다.
  client/src/components/headerDropdown/HeaderDropdown.tsx
Labels: FE

#388 Design: 메인 포토 아이템 대체 이미지 사이즈 조정
  client/src/assets/whiteNoImg.png
  client/src/components/photoItem/PhotoItem.styled.tsx
  client/src/components/photoItem/PhotoItem.tsx
Labels: FE
